export const movies = [
  'The Warriors',
  'Raising Arizona',
  'Con Air',
  'The Fly',
  // 'Terrifier',
  // 'Tokyo Gore Police',
  // 'Neon Deamon',
  // 'Big Trouble In Little China',
  // 'Escape From New York',
  'Scanners',
  'Videodrome',
  'Robocop',
  'How High',
  // 'Half baked',
  'Ghostbusters',
  'Commando',
  'Scary Movie 2',
  'Leon: The Professional',
  'Starship Troopers',
  // 'They Live',
  // 'Way of the Gun',
  'Rambo',
  'Predator',
  'Total Recall',
  'Prince OF Darkness',
  'The Mouth of Madness',
  'Belko Experiment',
  'Mayhem',
  // 'Judgement Night',
  'Tales From The Hood',
  // 'People Under The Stairs',
  'Friday',
  // 'Demon Knight',
  'The Rock',
  'Buckaroo Banzai',
  // 'Timecop',
  // 'The Running Man',
  'Best in Show',
  'Funny Games',
  // 'Maximum Overdrive',
  // 'Romeo Must Die',
  // 'Tommy Boy',
  'Caddyshack',
  'Re-Animator',
  'Martyrs',
  'Dead Presidents',
  'The Ring',
  'The Goonies',
  'Brainscan',
  'Fist of Legend',
  'Kung Fu Hustle',
  'Ong-Bak: The Thai Warrior',
  'Bloodsport',
  'Heavyweights',
  // 'The Raid: Redemption',
  'The Night Comes for Us',
  'Rubber',
  'Dawn of the Dead',
  'V/H/S/2',
  'Rush Hour',
  'Near Dark',
  // 'Kalifornia',
  'Ichi the Killer',
  'Final Destination 3',
  "The 'Burbs",
  'The Lost Boys',
  'The Warriors',
  "The Devil's Rejects",
  'House of 1000 Corpses',
  '31',
  'Soldier',
  'Escape from L.A.',
  'Basketball',
  'Lethal Weapon',
  'Edge of Tomorrow',
  'The 13th Warrior',
  'The Last Samurai',
  'Hot Fuzz',
  'Dredd',
  'Blade',
  'Battle Royale',
  'Kiss Kiss Bang Bang',
  'Bad Boys II',
  'The Hills Have Eyes',
  'Critters',
  'Troll 2',
  'Gremlins',
  'Die Hard',
  'Chucky',
  'Friday the 13th',
  'A Nightmare on Elm Street',
  'The Evil Dead',
  'Evil Dead',
  'Army of Darkness',
  'Hellraiser',
  'The Cabin in the Woods',
  'Rocky',
  'Dracula 3000',
  'My Bloody Valentine',
  'Poltergeist',
  'Johnny Mnemonic',
  'Point Break',
  'Dreamscape',
  'RoboCop',
  'Judge Dredd',
  'Jeepers Creepers',
  'The Wicker Man',
  'Killer Klowns from Outer Space',
  'Minority Report',
  'Hereditary',
  'Texas Chainsaw',
  'Puppet Master',
  'Bone Tomahawk',
  'Tremors',
  'Children of the Corn',
  'Cube',
  'The Girl with All the Gifts',
  '2046',
  'Children of Men',
  'Wet Hot American Summer',
  "Bill & Ted's Excellent Adventure",
  'Peninsula',
  'Indiana Jones and the Temple of Doom',
  'John Wick',
  'Upgrade',
  'The Fifth Element',
  'Bloodsport',
  'Bio-Dome',
  'The Golden Child',
  'Ghostbusters',
  'The Cell',
  'The Fall',
  'Edward Scissorhands',
  'Overlord',
  'I Heart Huckabees',
  "Wayne's World"
];
