export const movies = [
  'The Warriors',
  'Raising Arizona',
  'Con Air',
  'The Fly',
  // 'Terrifier',
  // 'Tokyo Gore Police',
  // 'Neon Deamon',
  // 'Big Trouble In Little China',
  'Escape From New York',
  'Scanners',
  'Videodrome',
  'Robocop',
  'How High',
  // 'Half baked',
  'Ghostbusters',
  'Commando',
  'Scary Movie 2',
  'Leon: The Professional',
  'Starship Troopers',
  // 'They Live',
  // 'Way of the Gun',
  'Rambo',
  'Predator',
  'Total Recall',
  'Prince OF Darkness',
  'The Mouth of Madness',
  'Belko Experiment',
  'Mayhem',
  // 'Judgement Night',
  'Tales From The Hood',
  // 'People Under The Stairs',
  'Friday',
  // 'Demon Knight',
  'The Rock',
  // 'Buckaroo Banzai',
  'Timecop',
  // 'The Running Man',
  'Best in Show',
  'Funny Games',
  // 'Maximum Overdrive',
  'Romeo Must Die',
  // 'Tommy Boy',
  'Caddyshack',
  'Re-Animator',
  'Martyrs',
  'Dead Presidents',
  'The Ring',
  'The Goonies',
  'Brainscan',
  'Fist of Legend',
  'Kung Fu Hustle',
  'Ong-Bak: The Thai Warrior',
  'Bloodsport',
  'Heavyweights',
  'The Raid',
  'The Night Comes for Us',
  'Rubber',
  'Dawn of the Dead',
  'V/H/S/2',
  'Rush Hour'
];
