export const movies = [
  'The Warriors',
  'Raising Arizona',
  'Con Air',
  'The Fly',
  'Big Trouble In Little China',
  'Escape From New York',
  'Scanners',
  'Videodrome',
  'Robocop',
  'How High',
  'Half baked',
  'Ghostbusters',
  'Commando',
  'Scary Movie 2',
  'Leon: The Professional',
  'Starship Troopers',
  'They Live',
  'Way of the Gun',
  'Rambo',
  'Predator',
  'Total Recall',
  'Prince OF Darkness',
  'The Mouth of Madness',
  'Belko Experiment',
  'Mayhem',
  'Judgement Night',
  'Tales From The Hood',
  'People Under The Stairs',
  'Friday',
  'Demon Knight',
  'The Rock',
  'Buckaroo Banzai'
];
